#! /bin/sh
. `dirname $0`/lib/test_utils.sh
. perf/lib/massif.sh
which valgrind >/dev/null || { echo "No valgrind found." >&2; exit 1; }

if [ -n "$DIFF_TEST" ]
then
	echo "git diff --no-index perf_results/massif/${DIFF_TEST}-32_${BUILDCFG}.massif perf_results/massif/${DIFF_TEST}-64_${BUILDCFG}.massif"
	exit 0
fi

get_confirmation

for ARCHBITS in $ALL_ARCHBITS
do
	measure_with_massif
done

echo "# Performance measurement done. ################################" >&2
