#! /bin/sh
. `dirname $0`/lib/test_utils.sh
. perf/lib/perf.sh
which perf >/dev/null || { echo "No perf found." >&2; exit 1; }
BUILDCFG="optimized"

# DIFF COMMAND
if [ -n "$DIFF_TEST" ]
then
	echo "perf diff perf_results/perf/${DIFF_TEST}-32_${BUILDCFG}.perf perf_results/perf/${DIFF_TEST}-64_${BUILDCFG}.perf | c++filt | less"
	exit 0
fi

get_confirmation

for ARCHBITS in $ALL_ARCHBITS
do
	measure_with_perf
done

echo "# Performance measurement done. ################################" >&2
