#! /bin/sh
. `dirname $0`/lib/test_utils.sh
. perf/lib/valgrind.sh
which valgrind >/dev/null || { echo "No valgrind found." >&2; exit 1; }

if [ -n "$DIFF_TEST" ]
then
	echo "git diff --no-index perf_results/valgrind/${DIFF_TEST}-32_${BUILDCFG}.valgrind perf_results/valgrind/${DIFF_TEST}-64_${BUILDCFG}.valgrind"
	echo "memory summary: find valgrind/ -print -iname '*.valgrind' -exec sed -n '/HEAP SUMMARY/,/Checked/p' {} \;"
	exit 0
fi

get_confirmation

for ARCHBITS in $ALL_ARCHBITS
do
	measure_with_valgrind
done

echo "# Performance measurement done. ################################" >&2
