#! /bin/sh
. `dirname $0`/lib/common.sh
([ "$1" = '--help' ] || [ "$1" = '-h' ]) && { show_common_usage; exit 0; }
which valgrind >/dev/null || { echo "No valgrind found." >&2; exit 1; }

if [ -n "$DIFF_TEST" ]
then
	echo "git diff --no-index perf_results/massif/${DIFF_TEST}-32_${BUILDCFG}.massif perf_results/massif/${DIFF_TEST}-64_${BUILDCFG}.massif"
	exit 0
fi

get_confirmation

for ARCHBITS in 64 32
do
	BUILDCFG="debug"
	SCONSFLAGS="--ignore-missing --with-src-boost=3rdparty/boost --with-src-zlib=3rdparty/zlib --with-bin-openssl=3rdparty/openssl --build-cfg=$BUILDCFG --archbits=$ARCHBITS" # --warnlevel=medium --enable-Trace" # --config=force
	build `cat $ALL_TESTS`
	warmup `cat $ALL_TESTS`

	##
	# MEASUREMENT
	#
	progress "VALGRIND-MASSIF-BASED MEASUREMENT ..."
	cat $ALL_TESTS | while read TESTNAME
	do
		echo "#------------------------------------------------------------------------" >&2
		echo "# Running test $TESTNAME ... ########################" >&2
		RESULT=$PERF_DIR/massif/${TESTNAME}-${ARCHBITS}_${BUILDCFG}.massif
        RUNPARAMS="-x valgrind -x '--tool=massif' -x '--time-unit=B' -x '--massif-out-file=$RESULT' -x '--stacks=yes'"
		mkdir -p `dirname $RESULT`
		( set -x; scons $SCONSFLAGS --run-force --runparams="${RUNPARAMS} -- -all" $TESTNAME >$PERF_DIR/massif/${TESTNAME}-${ARCHBITS}_${BUILDCFG}.log 2>&1) || { echo "Test $TESTNAME with ARCHBITS=$ARCHBITS failed." >&2; exit 1; }
	done
done

echo "# Performance measurement done. ################################" >&2
