#! /bin/sh
. `dirname $0`/lib/test_utils.sh
. perf/lib/time.sh
BUILDCFG="optimized"

# DIFF COMMAND
if [ -n "$DIFF_TEST" ]
then
	echo "git diff --no-index perf_results/time/${DIFF_TEST}-32_${BUILDCFG}.csv perf_results/time/${DIFF_TEST}-64_${BUILDCFG}.csv"
	exit 0
fi

get_confirmation

for ARCHBITS in $ALL_ARCHBITS
do
	measure_with_time
done

echo "# Performance measurement done. ################################" >&2
