#! /bin/sh
. `dirname $0`/lib/common.sh
BUILDCFG="optimized"
which perf >/dev/null || { echo "No perf found." >&2; exit 1; }

# DIFF COMMAND
if [ -n "$DIFF_TEST" ]
then
    # TODO
	echo "perf diff perf_results/perf_stat/${DIFF_TEST}-32_${BUILDCFG}.perf perf_results/perf_stat/${DIFF_TEST}-64_${BUILDCFG}.perf | c++filt | less"
	exit 0
fi

get_confirmation

for ARCHBITS in 64 32
do
	SCONSFLAGS="--ignore-missing --with-src-boost=3rdparty/boost --with-src-zlib=3rdparty/zlib --with-bin-openssl=3rdparty/openssl --build-cfg=$BUILDCFG --archbits=$ARCHBITS" # --warnlevel=medium --enable-Trace" # --config=force 
	build `cat $ALL_TESTS`
	warmup `cat $ALL_TESTS`

	##
	# MEASUREMENT
	#
	progress "PERF-STAT MEASUREMENT ..."
	cat $ALL_TESTS | while read TESTNAME
	do
		echo "#------------------------------------------------------------------------" >&2
		echo "# Running test $TESTNAME ... ########################" >&2
		RESULT=$PERF_DIR/perf_stat/${TESTNAME}-${ARCHBITS}_${BUILDCFG}.perf
		mkdir -p `dirname $RESULT`
		#touch $RESULT # needed
		( set -x; scons $SCONSFLAGS --run-force --runparams="-x perf -x stat -x -d -x '-o$RESULT' -x '-r 20' -- -all" $TESTNAME >$PERF_DIR/perf_stat/${TESTNAME}-${ARCHBITS}_${BUILDCFG}.log 2>&1) || { echo "Test $TESTNAME with ARCHBITS=$ARCHBITS failed." >&2; exit 1; }
	done
done

echo "# Performance measurement done. ################################" >&2
